"""Pydantic schemas for SkillPilot models, skills, and API requests."""
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class SkillDefinition(BaseModel):
    """Represents a capability skill parsed from skills.md."""
    id: str = Field(..., description="Unique identifier for the skill (e.g., code_analysis)")
    name: str = Field(..., description="Human-readable title of the skill")
    description: str = Field(..., description="Summary of what the skill does")
    when_to_use: List[str] = Field(default_factory=list, description="Usage triggers and matching criteria")
    input_spec: str = Field(..., description="Expected inputs required by the skill")
    output_spec: List[str] = Field(default_factory=list, description="Mandatory output elements")
    constraints: List[str] = Field(default_factory=list, description="Rules and safety restrictions")


class ChatRequest(BaseModel):
    """User request payload sent to the agent."""
    query: str = Field(..., description="User instruction or prompt")
    code: Optional[str] = Field(default=None, description="Optional code snippet or context")
    session_id: str = Field(default="default", description="Conversation thread identifier for memory")


class ChatResponse(BaseModel):
    """Structured response returned by SkillPilot."""
    success: bool = True
    session_id: Optional[str] = Field(default="default", description="Active conversation session ID")
    selected_skill: Optional[str] = Field(default=None, description="ID of the primary skill chosen by the router")
    supporting_skills: List[str] = Field(default_factory=list, description="Supporting skills if applicable")
    skill_chain: List[str] = Field(default_factory=list, description="Ordered sequence of executed skills")
    step_results: List[Dict[str, Any]] = Field(default_factory=list, description="Results from each chain step")
    execution_history: List[Dict[str, Any]] = Field(default_factory=list, description="Prior conversational turn history")
    response: str = Field(..., description="Formatted answer generated by the skill pipeline")
    is_valid: bool = Field(default=True, description="Whether the output passed validation rules")
    validation_notes: Optional[str] = Field(default=None, description="Validation or guardrail feedback")
    error: Optional[str] = Field(default=None, description="Error message if execution failed")


class ValidationResult(BaseModel):
    """Result of validating an executed skill response against its contract."""
    is_valid: bool
    missing_elements: List[str] = Field(default_factory=list)
    feedback: Optional[str] = None


class EvaluationItem(BaseModel):
    """Represents a benchmark test case for agent evaluation."""
    id: int
    category: str
    query: str
    code: Optional[str] = None
    expected_skill: Optional[str] = None
    expected_chain: Optional[List[str]] = None
    is_negative: bool = False
    description: str = ""


class EvaluationResultItem(BaseModel):
    """Result of evaluating a single benchmark query."""
    item_id: int
    category: str
    query: str
    expected_skill: Optional[str]
    actual_skill: Optional[str]
    expected_chain: Optional[List[str]]
    actual_chain: List[str] = Field(default_factory=list)
    skill_selection_correct: bool
    chain_correct: bool
    execution_valid: bool
    response_useful: bool
    latency_ms: float
    output_length: int
    error: Optional[str] = None


class EvaluationSummary(BaseModel):
    """Aggregated evaluation metrics across the benchmark suite."""
    total_queries: int
    matched_queries: int
    negative_queries: int
    multi_skill_queries: int

    # Core Academic Metrics
    skill_selection_accuracy: float = Field(..., description="Percentage of queries routed to the correct skill")
    execution_accuracy: float = Field(..., description="Percentage of executed skills passing validation")
    invalid_request_handling: float = Field(..., description="Percentage of off-domain queries properly rejected")
    multi_skill_accuracy: float = Field(..., description="Percentage of chained workflows correctly sequenced")
    response_quality_score: float = Field(..., description="Percentage of responses satisfying completeness rules")

    # Latency Metrics (ms)
    avg_latency_ms: float
    min_latency_ms: float
    max_latency_ms: float
    p95_latency_ms: float
    total_time_seconds: float

    results: List[EvaluationResultItem] = Field(default_factory=list)

