"""Pydantic schemas for SkillPilot models, skills, and API requests."""
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field


class SkillDefinition(BaseModel):
    """Represents a capability skill parsed from skills.md."""
    id: str = Field(..., description="Unique identifier for the skill (e.g., code_analysis)")
    name: str = Field(..., description="Human-readable title of the skill")
    description: str = Field(..., description="Summary of what the skill does")
    when_to_use: List[str] = Field(default_factory=list, description="Usage triggers and matching criteria")
    input_spec: str = Field(..., description="Expected inputs required by the skill")
    output_spec: List[str] = Field(default_factory=list, description="Mandatory output elements")
    constraints: List[str] = Field(default_factory=list, description="Rules and safety restrictions")


class ChatRequest(BaseModel):
    """User request payload sent to the agent."""
    query: str = Field(..., description="User instruction or prompt")
    code: Optional[str] = Field(default=None, description="Optional code snippet or context")
    session_id: str = Field(default="default", description="Conversation thread identifier for memory")


class ChatResponse(BaseModel):
    """Structured response returned by SkillPilot."""
    success: bool = True
    session_id: Optional[str] = Field(default="default", description="Active conversation session ID")
    selected_skill: Optional[str] = Field(default=None, description="ID of the primary skill chosen by the router")
    supporting_skills: List[str] = Field(default_factory=list, description="Supporting skills if applicable")
    skill_chain: List[str] = Field(default_factory=list, description="Ordered sequence of executed skills")
    step_results: List[Dict[str, Any]] = Field(default_factory=list, description="Results from each chain step")
    execution_history: List[Dict[str, Any]] = Field(default_factory=list, description="Prior conversational turn history")
    response: str = Field(..., description="Formatted answer generated by the skill pipeline")
    is_valid: bool = Field(default=True, description="Whether the output passed validation rules")
    validation_notes: Optional[str] = Field(default=None, description="Validation or guardrail feedback")
    error: Optional[str] = Field(default=None, description="Error message if execution failed")


class ValidationResult(BaseModel):
    """Result of validating an executed skill response against its contract."""
    is_valid: bool
    missing_elements: List[str] = Field(default_factory=list)
    feedback: Optional[str] = None
